export const MESSAGE_REQUEST = 'MESSAGE_REQUEST';
export const MESSAGE_REQUEST_SUCCESS = 'MESSAGE_REQUEST_SUCCESS';
export const MESSAGE_REQUEST_FAIL = 'MESSAGE_REQUEST_FAIL';

export const USER_REQUEST_REQUEST = "USER_REQUEST_REQUEST"
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS"
export const USER_REQUEST_FAIL = "USER_REQUEST_FAIL"


